services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp1
      - mcp2
      - mcp3
    networks:
      - mcp_network
  mcp1:
    build: ./app
    container_name: mcp1
    ports:
      - "8001:8000"
    networks:
      - mcp_network

  mcp2:
    build: ./app
    container_name: mcp2
    ports:
      - "8002:8000"
    networks:
      - mcp_network

  mcp3:
    build: ./app
    container_name: mcp3
    ports:
      - "8003:8000"
    networks:
      - mcp_network

networks:
  mcp_network: