version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mcp:
    build: 
      context: ./backend
    ports:
      - "8000-8002:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 3
    depends_on:
      - redis

  client:
    build:
      context: ./client
    ports:
      - "8080:8000"
    depends_on:
      - mcp

volumes:
  redis_data: 