services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp1
      - mcp2
      - mcp3

  mcp1:
    build: ./app
    container_name: mcp1

  mcp2:
    build: ./app
    container_name: mcp2

  mcp3:
    build: ./app
    container_name: mcp3
